# GENERAL #
width=1000            # int   - image width (px)
height=1000           # int   - image height (px)
depth=1000            # int   - image depth / z‑size (px)
numOutputs=12         # int   - number of generated images

mode_count=2

mode1_mean=40            # float - target radius mean (px)
mode1_mean_delta=0.5       # float - allowable deviation in mean (px)
mode1_std_dev=1.0         # float - target radius std dev (px)
mode1_std_dev_delta=0.5    # float - allowable deviation in std dev (px)
mode1_count=1150             # int   - number of spheres
mode1_color_r=0            # int   - color R channel (0–255)
mode1_color_g=0            # int   - color G channel (0–255)
mode1_color_b=255          # int   - color B channel (0–255)

mode2_mean=20            # float - target radius mean (px)
mode2_mean_delta=0.5       # float - allowable deviation in mean (px)
mode2_std_dev=1.0         # float - target radius std dev (px)
mode2_std_dev_delta=0.5    # float - allowable deviation in std dev (px)
mode2_count=4500             # int   - number of spheres
mode2_color_r=255            # int   - color R channel (0–255)
mode2_color_g=0            # int   - color G channel (0–255)
mode2_color_b=0          # int   - color B channel (0–255)