# GENERAL #
width=1000            # int   - image width (px)
height=1000           # int   - image height (px)
depth=1000            # int   - image depth / z‑size (px)
numOutputs=12         # int   - number of generated images

# TOGGLE #
enable_group2=false    # bool  - set false to disable Group 2 spheres

# GROUP 1 #
group1_mean=78.0            # float - target radius mean (px)
group1_mean_delta=5       # float - allowable deviation in mean (px)
group1_std_dev=20.0         # float - target radius std dev (px)
group1_std_dev_delta=3    # float - allowable deviation in std dev (px)
group1_count=200             # int   - number of spheres
group1_color_r=0            # int   - color R channel (0–255)
group1_color_g=0            # int   - color G channel (0–255)
group1_color_b=255          # int   - color B channel (0–255)

# GROUP 2 #
group2_mean=10.0            # float - target radius mean (px)
group2_mean_delta=0.5       # float - allowable deviation in mean (px)
group2_std_dev=6.0          # float - target radius std dev (px)
group2_std_dev_delta=0.5    # float - allowable deviation in std dev (px)
group2_count=86             # int   - number of spheres
group2_color_r=255          # int   - color R channel (0–255)
group2_color_g=0            # int   - color G channel (0–255)
group2_color_b=0            # int   - color B channel (0–255)
